<a href="https://colab.research.google.com/github/JeremiahZhang/freecodecamp-intro-to-pandas/blob/master/2%20-%20Pandas%20Series%20exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![rmotr](https://user-images.githubusercontent.com/7065401/52071918-bda15380-2562-11e9-828c-7f95297e4a82.png)
<hr style="margin-bottom: 40px;">

# Pandas Series exercises


In [1]:
# Import the numpy package under the name np
import numpy as np

# Import the pandas package under the name pd
import pandas as pd

# Print the pandas version and the configuration
print(pd.__version__)

1.3.5


![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series creation

### Create an empty pandas Series

In [3]:
# your code goes here
pd.Series()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  


Series([], dtype: float64)

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X python list convert it to an Y pandas Series

In [4]:
# your code goes here
x = ['a', 'b', 'c']
print(x)

['a', 'b', 'c']


In [5]:
y = pd.Series(x)
print(y, type(y))

0    a
1    b
2    c
dtype: object <class 'pandas.core.series.Series'>


![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, name it 'My letters'

In [7]:
# your code goes here
y.name = 'my letters'

y

0    a
1    b
2    c
Name: my letters, dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its values


In [8]:
# your code goes here
x = y
x.values

array(['a', 'b', 'c'], dtype=object)

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series indexation

### Assign index names to the given X pandas Series


In [ ]:
X = pd.Series(['A','B','C'])
index_names = ['first', 'second', 'third']

X.index = index_names
X

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its first element


In [19]:
# your code goes here
X = pd.Series(list(('a', 'b', 'c')), index=['1st', '2nd', '3rd'])

X['1st']

'a'

In [20]:
X[0]

'a'

In [21]:
X.iloc[1]

'b'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show its last element


In [23]:
# your code goes here
X.iloc[-1]
X[-1]
X['3rd']

'c'

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show all middle elements


In [24]:
# your code goes here
x[:] # all the element

First     a
Second    b
Third     c
dtype: object

In [25]:
x[1:-1] # show all middle elements

Second    b
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the elements in reverse position


In [26]:
# your code goes here
X

1st    a
2nd    b
3rd    c
dtype: object

In [27]:
X[::-1]

3rd    c
2nd    b
1st    a
dtype: object

In [28]:
X.iloc[::-1]

3rd    c
2nd    b
1st    a
dtype: object

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the first and last elements


In [29]:
# your code goes here
X[[0, -1]]

1st    a
3rd    c
dtype: object

In [30]:
X[['1st', '3rd']]

1st    a
3rd    c
dtype: object

In [31]:
X.iloc[[0, -1]]

1st    a
3rd    c
dtype: object

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series manipulation

### Convert the given integer pandas Series to float


In [32]:
# your code goes here
X = pd.Series([1,2,3,4,5], index=['1st','2nd','3rd','4th','5th'])

pd.Series(X, dtype=np.float)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  after removing the cwd from sys.path.


1st    1.0
2nd    2.0
3rd    3.0
4th    4.0
5th    5.0
dtype: float64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Reverse the given pandas Series (first element becomes last)

In [33]:
# your code goes here
X

1st    1
2nd    2
3rd    3
4th    4
5th    5
dtype: int64

In [34]:
X[::-1]

5th    5
4th    4
3rd    3
2nd    2
1st    1
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Order (sort) the given pandas Series


In [37]:
# your code goes here
X = pd.Series([3,4,5,1,2], index=['three','forth','fifth','first','second'])

In [38]:
X

three     3
forth     4
fifth     5
first     1
second    2
dtype: int64

In [40]:
X = X.sort_values()
X

first     1
second    2
three     3
forth     4
fifth     5
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, set the fifth element equal to 10


In [41]:
# your code goes here
X['fifth'] = 10
X

first      1
second     2
three      3
forth      4
fifth     10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, change all the middle elements to 0


In [42]:
# your code goes here
X

first      1
second     2
three      3
forth      4
fifth     10
dtype: int64

In [44]:
X[1:-1] = 0
X

first      1
second     0
three      0
forth      0
fifth     10
dtype: int64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, add 5 to every element


In [45]:
# your code goes here
X

first      1
second     0
three      0
forth      0
fifth     10
dtype: int64

In [46]:
X + 5

first      6
second     5
three      5
forth      5
fifth     15
dtype: int64

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Series boolean arrays (also called masks)

### Given the X pandas Series, make a mask showing negative elements


In [50]:
# your code goes here

x = np.arange(10)
x = x - x.mean()

In [51]:
x

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [52]:
mask = x <= 0
mask

array([ True,  True,  True,  True,  True, False, False, False, False,
       False])

In [53]:
x[mask]

array([-4.5, -3.5, -2.5, -1.5, -0.5])

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get the negative elements


In [ ]:
# your code goes here
x[mask]

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than 3


In [54]:
# your code goes here
x

array([-4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [55]:
X = pd.Series(x)
X

0   -4.5
1   -3.5
2   -2.5
3   -1.5
4   -0.5
5    0.5
6    1.5
7    2.5
8    3.5
9    4.5
dtype: float64

In [56]:
mask = X > 3
X[mask]

8    3.5
9    4.5
dtype: float64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers higher than the elements mean

In [57]:
# your code goes here
mask = X > X.mean()
X[mask]

5    0.5
6    1.5
7    2.5
8    3.5
9    4.5
dtype: float64

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, get numbers equal to 2 or 10


In [58]:
# your code goes here
mask = (X == 2) | (X == 2.5)
X[mask]

7    2.5
dtype: float64

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Logic functions

### Given the X pandas Series, return True if none of its elements is zero

In [59]:
# your code goes here
X

0   -4.5
1   -3.5
2   -2.5
3   -1.5
4   -0.5
5    0.5
6    1.5
7    2.5
8    3.5
9    4.5
dtype: float64

In [60]:
X.all()

True

In [61]:
X = X - 0.5
X

0   -5.0
1   -4.0
2   -3.0
3   -2.0
4   -1.0
5    0.0
6    1.0
7    2.0
8    3.0
9    4.0
dtype: float64

In [62]:
X.all()

False

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, return True if any of its elements is zero


In [63]:
# your code goes here
X.any()

True

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)

## Summary statistics

### Given the X pandas Series, show the sum of its elements


In [64]:
# your code goes here
X

0   -5.0
1   -4.0
2   -3.0
3   -2.0
4   -1.0
5    0.0
6    1.0
7    2.0
8    3.0
9    4.0
dtype: float64

In [65]:
#np.sum(X)
X.sum()

-5.0

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the mean value of its elements

In [66]:
# your code goes here
X.mean()

-0.5

In [67]:
np.mean(X)

-0.5

![green-divider](https://user-images.githubusercontent.com/7065401/52071924-c003ad80-2562-11e9-8297-1c6595f8a7ff.png)

### Given the X pandas Series, show the max value of its elements

In [68]:
# your code goes here
X.max()

4.0

In [69]:
np.max(X)

4.0

![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)